# Hint: Use the Karabiner Event Viewer to identify the names of each key you want to map

layers:
  base:
    description: "Base Layer"
    output:
    - 3-2: j
    - 3-3: d
    - 3-4: u
    - 3-5: a
    - 3-6: x
    - 3-7: p
    - 3-8: h
    - 3-9: l
    - 3-10: m
    - 3-11: w
    - 3-12: q
    - 3-13: ß
    - 3-13: '&#x000D;' # return

    - 4-2: c
    - 4-3: t
    - 4-4: i
    - 4-5: e
    - 4-6: o
    - 4-7: b
    - 4-8: n
    - 4-9: r
    - 4-10: s
    - 4-11: g

    - 5-3: f
    - 5-4: v
    - 5-5: ü
    - 5-6: ä
    - 5-7: ö
    - 5-8: y
    - 5-9: z
    - 5-10: ,
    - 5-11: .
    - 5-12: k

    - 6-5: ' ' # space

  shift:
    description: "Shift Layer"
    output:
    - 3-2: J
    - 3-3: D
    - 3-4: U
    - 3-5: A
    - 3-6: X
    - 3-7: P
    - 3-8: H
    - 3-9: L
    - 3-10: M
    - 3-11: W
    - 3-12: Q
    - 3-13: ẞ
    - 3-13: '&#x000D;' # return

    - 4-2: C
    - 4-3: T
    - 4-4: I
    - 4-5: E
    - 4-6: O
    - 4-7: B
    - 4-8: N
    - 4-9: R
    - 4-10: S
    - 4-11: G

    - 5-3: F
    - 5-4: V
    - 5-5: Ü
    - 5-6: Ä
    - 5-7: Ö
    - 5-8: Y
    - 5-9: Z
    - 5-10: ,
    - 5-11: .
    - 5-12: K

    - 6-5: ' ' # space

  coding:
    description: "Coding Layer"
    trigger: [[grave_accent_and_tilde], [some_other_key]]
    mappings:
    - a: '\'
    - s: '/'

  numbers:
    description: "Numbers Layer"
    trigger: grave_accent_and_tilde
    mappings:
    - spacebar: 0
    - m: 1
    - comma: 2
    - period: 3
    - j: 4
    - k: 5
    - l: 6
    - u: 7
    - i: 8
    - o: 9

  navigation_plus:
    description: "Navigation Layer Plus"
    trigger: [left_command, spacebar]
    mappings:
    - j:
        key_code: left_arrow
        modifier: left_option
    - k:
        key_code: down_arrow
        modifier: left_option
    - l:
        key_code: right_arrow
        modifier: left_option
    - i:
        key_code: up_arrow
        modifier: left_option



  navigation:
    description: "Navigation Layer"
    trigger: left_command
    mappings:
    - j: left_arrow
    - k: down_arrow
    - l: right_arrow
    - i: up_arrow

    - m: return_or_enter
    - u: delete_or_backspace
    - o: delete_forward

    - description: "home"
      from: h
      to:
        key_code: left_arrow
        modifier: left_command

    - description: "end"
      from: semicolon
      to:
        key_code: right_arrow
        modifier: left_command

    - description: "forward tab"
      from: w
      to: tab

    - description: "backward tab"
      from: q
      to:
        key_code: tab
        modifier: right_shift

