# This file represents the used keyboard. In my case it's a German Apple Keyboard.

layout:
- [escape, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12]
- [non_us_backslash, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, hyphen, equal_sign, delete_or_backspace]
- [tab, q, w, e, r, t, y, u, i, o, p, open_bracket, close_bracket, return_or_enter]
- [caps_lock, a, s, d, f, g, h, j, k, l, semicolon, quote, backslash]
- [left_shift, grave_accent_and_tilde, z, x, c, v, b, n, m, comma, period, slash, right_shift]
- [fn, left_control, left_alt, left_command, spacebar, right_command, right_alt, left_arrow, up_arrow, down_arrow, right_arrow]
